site_name: Lattice

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/favicon.ico  # Optional: set your logo
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
